name: Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

env:
  # Docker Hub registry
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_IMAGE: bjornftw/transip-domain-catcher
  # GitHub Container Registry
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE: bjornftw/transip-domain-catcher

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image to Docker Hub
        id: build-and-push-dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}:${{ github.event.inputs.version }}
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKERHUB_IMAGE }}:latest

      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image to GitHub Container Registry
        id: build-and-push-ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}:${{ github.event.inputs.version }}
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE }}:latest